version: '3'
services:
  mongo:
    image: 'mongo'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 829452A23J123hHjkssuekal8976dwsDtvfFw
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: lkJHkjlMIUjklhgSEGjhfggHLKJhh65&9780698

  node-app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
